### ISSUE TITLE
How to configure the external mongodb user password?

### ISSUE THREAD

**Issue by shaojielinux** [magneticio/vamp2setup#30]
How to configure the external mongodb user password?

**Comment by shaojielinux** [comment]
error

**03:49:34.533 [hz.main.partition-operation.thread-3] DEBUG org.mongodb.driver.protocol.command - Sending command {find : BsonString{value='datakeycontext'}} to database test on connection [connectionId{localValue:6, serverValue:28}] to server 10.101.8.167:27017
03:49:34.533 [hz.main.partition-operation.thread-3] ERROR i.v.p.impl.PersistenceMapStore - Error while loading { 'key' : 'project=default' }
com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'command find requires authentication' on server 10.101.8.167:27017
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:720)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:709)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:433)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:406)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:709)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:81)
	at com.mongodb.Mongo.execute(Mongo.java:810)
	at com.mongodb.Mongo$2.execute(Mongo.java:797)
	at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
	at com.mongodb.FindIterableImpl.iterator(FindIterableImpl.java:200)
	at com.mongodb.FindIterableImpl.iterator(FindIterableImpl.java:37)
	at scala.collection.convert.Wrappers$JIterableWrapper.iterator(Wrappers.scala:51)
	at scala.collection.IterableLike.isEmpty(IterableLike.scala:80)
	at scala.collection.IterableLike.isEmpty$(IterableLike.scala:79)
	at scala.collection.AbstractIterable.isEmpty(Iterable.scala:54)
	at scala.collection.TraversableLike.headOption(TraversableLike.scala:412)
	at scala.collection.TraversableLike.headOption$(TraversableLike.scala:412)
	at scala.collection.AbstractTraversable.headOption(Traversable.scala:104)
	at io.vamp.persistence.impl.MongoDbConnector.getValue(MongoDbConnector.scala:113)
	at io.vamp.persistence.impl.PersistenceMapStore.$anonfun$load$1(PersistenceMapStore.scala:136)
	at scala.util.Try$.apply(Try.scala:209)
	at io.vamp.persistence.impl.PersistenceMapStore.load(PersistenceMapStore.scala:136)
	at io.vamp.persistence.impl.PersistenceMapStore.load(PersistenceMapStore.scala:21)
	at com.hazelcast.map.impl.MapStoreWrapper.load(MapStoreWrapper.java:152)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindStore.load(WriteBehindStore.java:206)
	at com.hazelcast.map.impl.mapstore.writebehind.WriteBehindStore.load(WriteBehindStore.java:56)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.loadRecordOrNull(DefaultRecordStore.java:433)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.get(DefaultRecordStore.java:636)
	at com.hazelcast.map.impl.operation.GetOperation.run(GetOperation.java:41)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)**
